### ISSUE TITLE
Encountering 'javascript.operators.logical_nullish_assignment' is unknown after upgrading to v2.0.2

### ISSUE THREAD

**Issue by ICodeMyOwnLife** [wessberg/browserslist-generator#13]
Hello authors,

I encountered the following error after upgrading `rollup-plugin-ts` to 3.2.0 (and hence `browserslist-generator` was upgraded to 2.0.2)

```
[!] TypeError: The given feature: 'javascript.operators.logical_nullish_assignment' is unknown. It must be a valid Caniuse or MDN feature!
    at assertKnownFeature (file:///Users/fred.truong/Code/me/reporting-issues/node_modules/browserslist-generator/dist/esm/index.js:1150:15)
    at getFeatureSupport (file:///Users/fred.truong/Code/me/reporting-issues/node_modules/browserslist-generator/dist/esm/index.js:1169:5)
    at browserSupportForFeaturesCommon (file:///Users/fred.truong/Code/me/reporting-issues/node_modules/browserslist-generator/dist/esm/index.js:1292:25)
    at browsersWithSupportForFeatures (file:///Users/fred.truong/Code/me/reporting-issues/node_modules/browserslist-generator/dist/esm/index.js:955:33)
    at browsersWithSupportForEcmaVersion (file:///Users/fred.truong/Code/me/reporting-issues/node_modules/browserslist-generator/dist/esm/index.js:1035:20)
    at takeBrowserslistOrComputeBasedOnCompilerOptions (file:///Users/fred.truong/Code/me/reporting-issues/node_modules/rollup-plugin-ts/dist/esm/index.js:1847:61)
    at Object.options (file:///Users/fred.truong/Code/me/reporting-issues/node_modules/rollup-plugin-ts/dist/esm/index.js:9230:46)
    at async /Users/fred.truong/Code/me/reporting-issues/node_modules/rollup/dist/shared/rollup.js:25451:18
    at async getInputOptions (/Users/fred.truong/Code/me/reporting-issues/node_modules/rollup/dist/shared/rollup.js:25444:67)
    at async rollupInternal (/Users/fred.truong/Code/me/reporting-issues/node_modules/rollup/dist/shared/rollup.js:25385:72)
```

I guess it's due to [this line](https://github.com/wessberg/browserslist-generator/blob/a9f128c4f7f08eae76e39c68cdc5d5f1a37c1a8c/src/browserslist-generator/ecma-version.ts#L83) 

The error is thrown at [this line](https://github.com/wessberg/browserslist-generator/blob/a9f128c4f7f08eae76e39c68cdc5d5f1a37c1a8c/src/browserslist-generator/browserslist-generator.ts#L726)

It seems that `javascript.operators.logical_nullish_assignment` is not (any longer) a Caniuse or MDN feature. As I can see on [Caniuse](https://caniuse.com/?search=Nullish%20coalescing%20assignment) and [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment) it's called **Nullish coalescing assignment**

I created a minimal project to reproduce the issue [here](https://github.com/ICodeMyOwnLife/reporting-issues/tree/main/packages/logical_nullish_assignment)

Thanks.

**Comment by wessberg** [comment]
Hi there.
It looks like this changed in between v5.2.30 and 5.2.33 of `@mdn/browser-compat/data`. I would assume this would have been considered a breaking a change, but apparently this was published as a patch. I've gone ahead and updated this library to point to the updated feature name and published a new version on NPM. Thanks!
