### ISSUE TITLE
'javascript.builtins.Array.at' is unknown

### ISSUE THREAD

**Issue by jaswrks** [wessberg/browserslist-generator#16]
Occurs on Node 20.5.1 running 2.1.0.

```
TypeError: The given feature: 'javascript.builtins.Array.at' is unknown. It must be a valid Caniuse or MDN feature!
```

I noticed the MDN import changed to a glob `*` import in the latest release. Not sure if that has something to do with it, but I was getting some warnings about experimental use of JSON import assertions also. If I revert back to previous version of browserslist-generator, all is fine. Still get the warning about experimental import assertions, though.

**Comment by jaswrks** [comment]
```
(node:47818) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError: The given feature: 'javascript.builtins.Array.at' is unknown. It must be a valid Caniuse or MDN feature!
    at assertKnownFeature (.../node_modules/browserslist-generator/dist/esm/index.js:1175:15)
    at getFeatureSupport (.../node_modules/browserslist-generator/dist/esm/index.js:1194:5)
    at browserSupportForFeaturesCommon (.../node_modules/browserslist-generator/dist/esm/index.js:1317:25)
    at browsersWithSupportForFeatures (.../node_modules/browserslist-generator/dist/esm/index.js:974:33)
    at browsersWithSupportForEcmaVersion (.../node_modules/browserslist-generator/dist/esm/index.js:1058:20)
    at Module.default (.../dev/.files/bin/browserslist/index.mjs:62:46)
    at BrowsersList.update (.../dev/.files/bin/update.mjs:227:98)
    at async BrowsersList.run (.../dev/.files/bin/update.mjs:210:3)
    at async Object.handler (.../dev/.files/bin/update.mjs:859:5)
```

**Comment by mems** [comment]
I've got the same issue and I thing it's related to this line:
https://github.com/wessberg/browserslist-generator/blob/80d81a43462da37426ac08b4fff72f468ef4f495/src/browserslist-generator/browserslist-generator.ts#L3

When executed in Node 19.2 imported from an ES module, because of the [namespace import (* as)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#namespace_import), `compatData` is `Module {default: Accessor, Symbol(Symbol.toStringTag): "Module"}`
That means if you wan't to read `javascript.builtins.Array.at`, you need to access it as `compatData.default.javascript.builtins.Array.at` (throw the `default`).

**Comment by laverdet** [comment]
Thanks @mems, I patched this locally and it works:
```diff
diff --git a/dist/esm/index.js b/dist/esm/index.js
index 5f01ddfca542c54ffedced4d4489aff4843d6067..2180bc326bd27c4c0d088aa06af185aadbd0b22b 100644
--- a/dist/esm/index.js
+++ b/dist/esm/index.js
@@ -1,6 +1,6 @@
 import Browserslist from 'browserslist';
 import { feature, features } from 'caniuse-lite';
-import * as compatData from '@mdn/browser-compat-data' assert { type: 'json' };
+import compatData from '@mdn/browser-compat-data' assert { type: 'json' };
 import objectPath from 'object-path';
 import { coerce, lt, gt, gte, lte } from 'semver';
 import { UAParser } from 'ua-parser-js';
```

**Comment by jaswrks** [comment]
Thanks so much. Is there an ETA on when there will be a release available that patches this?

**Comment by mems** [comment]
I tried with the new version v3 but still have the same issue.

I tried to understand why this is not an blocking issue when release new versions ([since then we have have few more versions](https://github.com/wessberg/browserslist-generator/compare/v2.0.3...v3.0.0))
After investigating a bit, I found the problem. I think it's comes from how TypeScript handle import of JSON (but I'm not a TS user). I can easliy reproduce it when I using the [source of test suite of browserslist-generator](https://github.com/wessberg/browserslist-generator/blob/4cd748d5bbb0d6a34d6df471c8248f7e3fd7f36a/test/browserslist-generator.test.ts).

With the following `package.json`, execute `npm install`. Then run `npm run test` and `npm run test-ts`.

You will get something like:
```
> npm run test
[...]
ℹ tests 147
ℹ suites 0
ℹ pass 67
ℹ fail 80
ℹ cancelled 0
ℹ skipped 0
ℹ todo 0
ℹ duration_ms 1290.7176
[...]

> npm run test-ts
[...]
ℹ tests 147
ℹ suites 0
ℹ pass 147
ℹ fail 0
ℹ cancelled 0
ℹ skipped 0
ℹ todo 0
ℹ duration_ms 3270.8962
```

It fail with pure (lot of "TypeError [Error]: The given feature: '${feature}' is unknown. It must be a valid Caniuse or MDN feature!"), but it pass with TS.

<details>
<summary>package.json</summary>

It download `browserslist-generator.test.js` from the browserslist-generator repo, update an import (to use `browserslist-generator` instead of sources) and install `browserslist-generator`, `tsx` and `useragent-generator`

```json
{
  "name": "browserslist-generator-test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "prepare": "curl -s https://raw.githubusercontent.com/wessberg/browserslist-generator/refs/heads/master/test/browserslist-generator.test.ts | sed 's|../src/index.js|browserslist-generator|g' > browserslist-generator.test.js",
    "test": "node --test browserslist-generator.test.js",
    "test-ts": "node --import tsx --test browserslist-generator.test.js"
  },
  "type": "module",
  "dependencies": {
    "browserslist-generator": "^3.0.0",
    "tsx": "^4.19.2",
    "useragent-generator": "^1.1.0"
  }
}
```

</details>

**Comment by mems** [comment]
With the version 3.0.0, I use [patch-package](https://github.com/ds300/patch-package) with the following patch `patches/browserslist-generator+3.0.0.patch`:

```diff
This patch fix the issue https://github.com/wessberg/browserslist-generator/issues/16

diff --git a/node_modules/browserslist-generator/dist/index.js b/node_modules/browserslist-generator/dist/index.js
index a7640d4..76645e8 100644
--- a/node_modules/browserslist-generator/dist/index.js
+++ b/node_modules/browserslist-generator/dist/index.js
@@ -1,7 +1,7 @@
 // src/browserslist-generator/browserslist-generator.ts
 import Browserslist2 from "browserslist";
 import { feature as caniuseFeature, features as caniuseFeatures } from "caniuse-lite";
-import * as compatData from "@mdn/browser-compat-data" with { type: "json" };
+import compatData from "@mdn/browser-compat-data" with { type: "json" };
 import objectPath from "object-path";
 import { gt as gt2, gte as gte3, lt as lt2, lte as lte2 } from "semver";
 
```

**Comment by bosconian-dynamics** [comment]
Related: #19
